name: Send Email on Commit

on:
  push:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.outlook.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: '丘멆잺 Lembrete de Relat칩rio de produtividade 丘멆잺'
          body: |
            Ol치, ${{ github.event.pusher.email }}.\n
          
            Voc칡 acabou de fazer um commit no reposit칩rio.  
            N칚o se esque칞a de fazer o relat칩rio de produtividade para n칚o ter problemas com apontamentos
            e acumular faltas em PI.
            \n \n
            游뚿 Aten칞칚o 游뚿
          to: ${{ github.event.pusher.email }}
          from: 'no-reply@example.com'
