name: EC2 deploy

on:
  push:
    pull_request:
      branches:
        - main

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependences
        run: npm install
      
      - name: Run testes
        run: npm test

      - name: Rum build
        run: npm ruin build

      docker:
        runs-on: ubuntu-latest
        needs:
          - build
          - test
        steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}      
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              push: true
              tags: lucasrocha2704/ci-example:latest