name: Run Selenium Automation

on:
  push:
    branches:
      - main  # Ou outra branch desejada
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub Actions

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      # 1. Configuração do ambiente
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set author password
        id: author_password
        run: |
          case "${{ env.COMMIT_AUTHOR }}" in
            "lucasrocha2704") echo "commit_author_password=${{ secrets.PASSWORD.lucasrocha2704 }}" >> $GITHUB_ENV ;;
            "usuario2") echo "commit_author_password=${{ secrets.PASSWORD.usuario2 }}" >> $GITHUB_ENV ;;
            "usuario3") echo "commit_author_password=${{ secrets.PASSWORD.usuario3 }}" >> $GITHUB_ENV ;;
            # Adicione mais cases conforme necessário para cada usuário
            *) echo "commit_author_password=" >> $GITHUB_ENV ;; # Senha vazia caso o autor não seja reconhecido
          esac


      # 2. Verificar se o Google Chrome está instalado
      - name: Check if Google Chrome is installed
        id: chrome
        run: |
          if ! command -v google-chrome-stable &> /dev/null
          then
            echo "Google Chrome not found, installing..."
            sudo apt-get update -y
            sudo apt-get install -y wget
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
            sudo apt-get install -f -y  # Resolve dependências faltantes
          else
            echo "Google Chrome is already installed"
          fi

      # 3. Instalar dependências do Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Rodar o script de automação
      - name: Run Automation Script
        env:  
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }}
          COMMIT_AUTHOR_EMAIL: ${{ env.COMMIT_AUTHOR_EMAIL }}
          COMMIT_AUTHOR_PASSWORD: ${{ env.commit_author_password }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
          COMMIT_URL: ${{ env.COMMIT_URL }}
        run: |
<<<<<<< HEAD
          python /automacao-relatorio/main.py
=======
          python /automacao-relatorio/main.py
>>>>>>> origin
